pull_request_rules:
  - name: backport patches to stable/4.2.x
    conditions:
      - base=main
      - label=backport-to-4.2
    actions:
      backport:
        title: "[4.2.x] {{ title }} (backport #{{ number }})"
        branches:
          - stable/4.2.x

  - name: backport patches to stable/4.3.x
    conditions:
      - base=main
      - label=backport-to-4.3
    actions:
      backport:
        title: "[4.3.x] {{ title }} (backport #{{ number }})"
        branches:
          - stable/4.3.x


  - name: backport patches to stable/4.4.x
    conditions:
      - base=main
      - label=backport-to-4.4
    actions:
      backport:
        title: "[4.4.x] {{ title }} (backport #{{ number }})"
        branches:
          - stable/4.4.x
